version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: app_${APP_NAME}
    ports:
      - "${API_PORT}:9000"
    depends_on:
      - db

  db:
    image: mariadb:latest
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root

  queue-worker:
    image: app_${APP_NAME}
    entrypoint: >
      sh -c
        'php artisan optimize \
         && php artisan config:cache \
         && php artisan queue:work --tries=1 --timeout=90 --sleep=3 --max-time=3600 --memory=512'
    depends_on:
      - app

  crond:
    image: app_${APP_NAME}
    entrypoint: >
      sh -c  
         'mkdir -p /etc/cron.d \
          && touch /etc/cron.d/crontab \
          && echo "* * * * * php /var/www/html/artisan schedule:run >> /dev/null 2>&1" > /etc/cron.d/crontab \
          && crontab /etc/cron.d/crontab \
          && crond -f'
    depends_on:
      - app

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - app

  redis:
    image: redis:7.0.9-alpine3.17
    volumes:
      - ./docker/redis/data:/data